### ISSUE TITLE
does not start

### ISSUE THREAD

**Issue by robulanetteam** [CrazyShipOne/nextcloud_talk_pybot#3]
Hello! I did everything as in the instructions for Linux, but when starting it gives out this:

user@nextcloud:/tmp/nextcloud_talk_pybot$ ./start.sh
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/nextcloud_talk_pybot/ncbot/__main__.py", line 8, in <module>
    import ncbot.app as app
  File "/tmp/nextcloud_talk_pybot/ncbot/../ncbot/app.py", line 1, in <module>
    import ncbot.poll_runner as runner
  File "/tmp/nextcloud_talk_pybot/ncbot/../ncbot/poll_runner.py", line 6, in <module>
    from ncbot.log_config import logger
  File "/tmp/nextcloud_talk_pybot/ncbot/../ncbot/log_config.py", line 6, in <module>
    level = logging.getLevelNamesMapping()[log_level]
AttributeError: module 'logging' has no attribute 'getLevelNamesMapping'

**Comment by CrazyShipOne** [comment]
My apology, I was on a long vacation without access to internet.

The project should be run with python version >= 3.11. I'll mention it in the document. 
Thanks!
